### ISSUE TITLE
Can't build without LTO

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_port_renesas_ek-ra8d1_llvm#1]
When LTO is disabled all sorts of strange errors appear during linking: unknown instruction, no space in flash, etc.

It's the same with LLVM 17  and LLVM 18 too.

@jeremy-baker Do you have any idea about it?

**Comment by jeremy-baker** [comment]
I have cloned the repo, and built the master branch, you don't seem to have garbage collection enabled in the linker settings (Linker CPP->Miscellaneous->Enable garbage collection of unused input sections (-gc-sections) ) which would explain the sections overflowing, and if I switch to using LLVM 18.1.3 then there are no error messages about unknown instructions.

**Comment by kisvegabor** [comment]
It did the trick! Thank you!

Tomorrow I'll test the performance difference with and without LTO. 

If you are interested, finally I could publish a [comparison of GCC, LLVM, and Ac6](https://www.linkedin.com/feed/update/urn:li:activity:7235374927598518272/).

**Comment by jeremy-baker** [comment]
In the article, the link to the AC6 project doesn't work ( https://github.com/lvgl/lv_port_renesas_ek-ra8d1_ac6 ), did you mean it to be :- 
https://github.com/lvgl/lv_port_renesas_ek-ra8d1_ac6_arm2d

**Comment by kisvegabor** [comment]
Thanks for pointing it out. I've renamed the repo to `..._ac6` instead for consistency (the LLVM project also has Arm2D).

I've also tested the performance without LTO. It's 2% slower than GCC (With LTO it was 20% faster)
